-- DEMO DATA FOR LOCAL DEVELOPMENT ONLY.
-- Every story is illustrative sample content (headlines start with "[Sample]"), not real reporting.
-- Timestamps are relative to "now" so the time tape always has lit slots.
-- Never run this against the production database:  npm run db:init && npm run db:seed
DELETE FROM articles WHERE id LIKE 'sample\_%' ESCAPE '\';
DELETE FROM pipeline_events WHERE article_id LIKE 'sample\_%' ESCAPE '\';
DELETE FROM article_translations WHERE article_id LIKE 'sample\_%' ESCAPE '\';
DELETE FROM article_charts WHERE article_id LIKE 'sample\_%' ESCAPE '\';
DELETE FROM feed_items WHERE id LIKE 'sample\_%' ESCAPE '\';

INSERT INTO articles (id, headline, summary, what_happened, why_it_matters, figures_dates, affected_entities, risks_uncertainty,
  category, georgia_related, source_links, trust_score, grammar_checked, fact_checked, status, published_at, created_at, updated_at) VALUES
('sample_01', '[Sample] National Bank of Georgia holds its refinancing rate steady', 'The central bank left its key rate unchanged and said inflation is tracking its target path.', 'The National Bank of Georgia''s Monetary Policy Committee kept the refinancing rate unchanged at its latest meeting. It said annual inflation remains close to target and that domestic demand is growing at a moderate pace.', 'Borrowing costs for Georgian households and businesses stay where they are for now. A steady rate also signals that policymakers see no need to respond to recent exchange-rate moves.', 'Refinancing rate: 8.0%
Inflation: 3.4% year on year
Next meeting: 11 December', 'National Bank of Georgia, Georgian banks, Borrowers', 'The decision depends on the inflation path holding; a sharp lari move or an energy price shock could change the outlook before the next meeting.', 'Economics', 1, '[{"title": "NBG press release: Monetary Policy Committee decision", "url": "https://nbg.gov.ge/en/media/news", "trust_score": 5.0}, {"title": "Georgia''s central bank keeps rate on hold", "url": "https://civil.ge/", "trust_score": 3.5}]', 95, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-4 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-4 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-4 minutes')),
('sample_02', '[Sample] Chipmaker unveils inference accelerator aimed at data centres', 'A new accelerator targets running trained models at lower power per query.', 'The company introduced a new accelerator designed for inference workloads in data centres. It said the part will ship to cloud customers next quarter and is built to cut power use per query compared with its previous generation.', 'Inference is now the largest share of AI computing demand. Lower running costs could change how cloud providers price AI services, and put pressure on rival chip makers.', 'Availability: next quarter
Claimed power saving: 30% per query', 'Cloud providers, Chip makers, AI developers', 'Performance and power figures are company claims and have not been independently benchmarked.', 'AI & Tech', 0, '[{"title": "Newsroom: new inference accelerator", "url": "https://blogs.nvidia.com/", "trust_score": 3.5}, {"title": "The new chip is built for running AI, not training it", "url": "https://www.theverge.com/", "trust_score": 3.5}, {"title": "What the new accelerator means for cloud AI", "url": "https://arstechnica.com/", "trust_score": 3.5}]', 69, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-9 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-9 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-9 minutes')),
('sample_03', '[Sample] Spot Bitcoin ETFs log a third straight day of net inflows', 'US-listed Bitcoin funds took in new money for a third consecutive session.', 'US-listed spot Bitcoin exchange-traded funds recorded net inflows for a third consecutive trading day, according to fund-flow data cited by two crypto outlets. Bitcoin traded higher over the same period.', 'Steady ETF inflows are a sign of institutional demand, which has become a main driver of Bitcoin''s price. A reversal would point to cooling appetite.', 'Net inflow, latest day: $412 million
Consecutive inflow days: 3', 'Bitcoin ETF issuers, Crypto exchanges, Investors', 'Daily flow figures are revised as issuers report; single-day data can mislead about the trend.', 'Crypto', 0, '[{"title": "Bitcoin ETFs extend inflow streak", "url": "https://www.coindesk.com/", "trust_score": 3.5}, {"title": "Spot Bitcoin ETFs see third day of inflows", "url": "https://www.theblock.co/", "trust_score": 3.5}]', 68, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-18 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-18 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-18 minutes')),
('sample_04', '[Sample] WTO trims its forecast for global goods trade growth', 'The trade body lowered its outlook, citing weaker demand and higher tariffs.', 'The World Trade Organization cut its forecast for growth in the volume of world merchandise trade, pointing to softer demand in major economies and the effect of higher tariffs. A wire report confirmed the revision.', 'Slower trade growth weighs on exporters and shipping lines, and can feed through to manufacturing output and port volumes.', 'Forecast revision: down 0.6 percentage points
New forecast: 1.9% volume growth', 'Exporters, Shipping lines, Manufacturing', 'Forecasts are sensitive to tariff decisions that are still being negotiated.', 'Global Trade', 0, '[{"title": "WTO: updated trade forecast", "url": "https://www.wto.org/", "trust_score": 5.0}, {"title": "WTO cuts global trade growth forecast", "url": "https://www.reuters.com/", "trust_score": 4.5}]', 95, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-33 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-33 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-33 minutes')),
('sample_05', '[Sample] European climate-tech startup closes a mid-sized Series B', 'A Berlin-based company raised new funding to expand production.', 'A European climate-technology startup announced a Series B round led by an existing investor. It plans to use the money to expand manufacturing and hire engineers, according to two European startup outlets.', 'Funding for climate hardware has been harder to come by than for software. A well-subscribed round suggests investors still back capital-intensive climate companies with a clear route to revenue.', 'Round: Series B
Amount raised: €45 million', 'Startup investors, Climate-tech companies', 'Round size was reported by the outlets from company statements; valuation was not disclosed.', 'VC & Startups', 0, '[{"title": "Climate-tech startup raises Series B", "url": "https://sifted.eu/", "trust_score": 3.5}, {"title": "Berlin startup lands \u20ac45 million", "url": "https://www.eu-startups.com/", "trust_score": 3.5}]', 68, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-47 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-47 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-47 minutes')),
('sample_06', '[Sample] Mortgage rates ease for a second week', 'Average 30-year mortgage rates edged lower, giving buyers modest relief.', 'Average 30-year fixed mortgage rates edged lower for a second week, according to industry data reported by two property outlets. Applications for purchase loans rose slightly.', 'Even small rate declines widen the pool of buyers who can afford a monthly payment, which can lift sales volumes after a slow period.', '30-year fixed average: 6.42%
Weekly change: down 0.06 points', 'Home buyers, Lenders, Home builders', 'One week of data is not a trend; rates track bond yields, which can reverse quickly.', 'Real Estate', 0, '[{"title": "Mortgage rates slip again", "url": "https://www.bisnow.com/", "trust_score": 3.5}, {"title": "Rates dip for second straight week", "url": "https://www.housingwire.com/", "trust_score": 3.5}]', 68, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-62 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-62 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-62 minutes')),
('sample_07', '[Sample] Retail brands shift budget from paid search to creator partnerships', 'A survey found a growing share of brands moving spend to creators.', 'A survey of retail marketers found a growing share plan to move budget from paid search towards creator partnerships next year. Two trade publications reported the findings.', 'Search costs have risen, and brands are testing whether creator content delivers cheaper customer acquisition. Agencies and platforms are adjusting their offers.', 'Brands planning to shift spend: 38%
Survey period: third quarter', 'Retail brands, Ad agencies, Creator platforms', 'Survey responses show intent, not actual spend, and the sample skews towards larger brands.', 'General', 0, '[{"title": "Brands move budget to creators", "url": "https://www.adweek.com/", "trust_score": 3.5}, {"title": "Why retailers are cooling on paid search", "url": "https://digiday.com/", "trust_score": 3.5}]', 63, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-95 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-95 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-95 minutes')),
('sample_08', '[Sample] Georgia''s annual inflation edges up in the latest reading', 'The statistics office reported a small monthly rise in consumer prices.', 'Georgia''s national statistics office, GeoStat, reported that consumer prices rose slightly over the month, lifting annual inflation by a fraction of a point. Food and transport were the main contributors.', 'Inflation affects the central bank''s rate decisions and household purchasing power. A rise toward the target ceiling would narrow room for rate cuts.', 'Annual inflation: 3.4%
Monthly change: up 0.3%', 'Georgian households, National Bank of Georgia', 'Monthly readings are volatile; the office revises figures when more data arrives.', 'Economics', 1, '[{"title": "GeoStat: consumer price index", "url": "https://www.geostat.ge/en", "trust_score": 5.0}, {"title": "Inflation ticks up in Georgia", "url": "https://civil.ge/", "trust_score": 3.5}]', 95, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-130 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-130 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-130 minutes')),
('sample_09', '[Sample] Research lab releases open weights for a new reasoning model', 'The model and a technical paper were published for researchers to reproduce.', 'A research lab published the weights of a new reasoning model together with a peer-reviewed paper describing its training. Independent outlets confirmed the release and the licence terms.', 'Open weights let universities and smaller companies study and build on the model, and can set a floor for what closed commercial models must offer.', 'Parameters: 70 billion
Licence: permissive, research and commercial use', 'AI researchers, Cloud providers, Start-ups', 'Benchmark claims in the paper have not yet been reproduced by third parties.', 'AI & Tech', 0, '[{"title": "Nature: reasoning model paper", "url": "https://www.nature.com/", "trust_score": 5.0}, {"title": "An open model that reasons", "url": "https://www.technologyreview.com/", "trust_score": 3.5}, {"title": "Lab opens up its newest model", "url": "https://techcrunch.com/", "trust_score": 3.5}]', 100, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-190 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-190 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-190 minutes')),
('sample_10', '[Sample] Federal Reserve holds rates and signals a patient approach', 'The Fed kept its policy range unchanged and said it will wait for more data.', 'The Federal Reserve''s policy committee left its target range unchanged and said it will judge future moves on incoming data on inflation and employment. The decision was reported by a wire service and a financial daily.', 'US rates anchor borrowing costs worldwide. A patient Fed supports steady conditions for bond and currency markets, including for emerging markets.', 'Target range: 4.25% to 4.50%
Vote: unanimous', 'US borrowers, Bond markets, Emerging-market currencies', 'The committee noted that the path depends on data; a surprise in inflation or jobs could shift expectations.', 'Economics', 0, '[{"title": "Federal Reserve statement", "url": "https://www.federalreserve.gov/newsevents/pressreleases.htm", "trust_score": 5.0}, {"title": "Fed holds rates, signals patience", "url": "https://www.reuters.com/", "trust_score": 4.5}, {"title": "Fed leaves rates unchanged", "url": "https://www.wsj.com/", "trust_score": 4.0}]', 100, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-300 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-300 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-300 minutes')),
('sample_11', '[Sample] Stablecoin issuer publishes its latest reserve attestation', 'The attestation shows reserves above the value of coins in circulation.', 'A major stablecoin issuer published its monthly reserve attestation, which an independent accounting firm prepared. It reports reserves, mostly short-dated government debt, above the value of tokens in circulation.', 'Reserve transparency is central to stablecoin trust and to how regulators treat them.', 'Reserves to liabilities: 102%', 'Stablecoin holders, Exchanges, Regulators', 'An attestation is a snapshot at one date and is not a full audit.', 'Crypto', 0, '[{"title": "Stablecoin reserves exceed liabilities", "url": "https://www.coindesk.com/", "trust_score": 3.5}, {"title": "Issuer posts reserve report", "url": "https://decrypt.co/", "trust_score": 3.5}]', 63, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-420 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-420 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-420 minutes')),
('sample_12', '[Sample] Georgia''s finance ministry completes a eurobond placement', 'The government raised funds in international markets at a lower yield than its last issue.', 'The Ministry of Finance of Georgia completed a placement of eurobonds in international markets. A financial news service reported that demand exceeded the amount on offer.', 'A lower borrowing cost reflects investor confidence in Georgia''s credit and reduces future interest bills for the budget.', 'Amount: $500 million
Oversubscription: 3x', 'Government of Georgia, International investors', 'Market conditions can change; the ministry has not published the final allocation table.', 'Economics', 1, '[{"title": "Ministry of Finance announcement", "url": "https://www.mof.ge/en", "trust_score": 5.0}, {"title": "Georgia sells eurobonds at lower yield", "url": "https://www.bloomberg.com/", "trust_score": 4.0}]', 95, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-540 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-540 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-540 minutes')),
('sample_13', '[Sample] Container freight rates drop as capacity returns to key routes', 'Spot rates on major routes fell for the fourth week in a row.', 'Spot container freight rates on the main Asia-Europe and trans-Pacific routes fell for a fourth consecutive week as vessel capacity returned to service. Two shipping publications reported the move.', 'Lower freight costs ease pressure on importers and retailers and can reduce goods inflation with a lag.', 'Index change, week: down 5%', 'Importers, Retailers, Shipping lines', 'Rates can rebound quickly if disruptions return or demand picks up before peak season.', 'Global Trade', 0, '[{"title": "Container rates fall again", "url": "https://theloadstar.com/", "trust_score": 3.5}, {"title": "Spot rates slide on key lanes", "url": "https://www.joc.com/", "trust_score": 3.5}]', 68, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-1560 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-1560 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-1560 minutes')),
('sample_14', '[Sample] Universities report a rise in applications for data-science degrees', 'Application numbers for data and AI programmes rose year on year.', 'Several universities reported more applications for data-science and AI degrees this year, according to two education publications. Demand is strongest for one-year master''s programmes.', 'Graduate hiring and course supply are adjusting to demand for AI skills, which affects employers'' recruiting plans.', 'Application growth: 21% year on year', 'Universities, Employers, Applicants', 'Application counts do not show how many students enrol or complete.', 'General', 0, '[{"title": "Data-science programmes see surge", "url": "https://www.edsurge.com/", "trust_score": 3.5}, {"title": "AI degrees draw record applicants", "url": "https://www.insidehighered.com/", "trust_score": 3.5}]', 68, 1, 1, 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now','-1700 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-1700 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-1700 minutes'));

INSERT INTO pipeline_events (article_id, stage, outcome, detail, created_at) VALUES
('sample_01', 'fact_check', 'ok', '{"score": 95, "breakdown": {"credibility": 40.0, "corroboration": 20, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 5.0, "claims": {"total": 4, "supported": 4, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-4 minutes')),
('sample_02', 'fact_check', 'ok', '{"score": 69, "breakdown": {"credibility": 28.0, "corroboration": 25, "primaryEvidence": 5, "claimSupport": 11.2, "penalties": 0}, "reasons": [], "independentSources": 3, "bestWeight": 3.5, "claims": {"total": 4, "supported": 3, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-9 minutes')),
('sample_03', 'fact_check', 'ok', '{"score": 68, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 3, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-18 minutes')),
('sample_04', 'fact_check', 'ok', '{"score": 95, "breakdown": {"credibility": 40.0, "corroboration": 20, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 5.0, "claims": {"total": 5, "supported": 5, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-33 minutes')),
('sample_05', 'fact_check', 'ok', '{"score": 68, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 3, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-47 minutes')),
('sample_06', 'fact_check', 'ok', '{"score": 68, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 3, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-62 minutes')),
('sample_07', 'fact_check', 'ok', '{"score": 63, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 10.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 2, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-95 minutes')),
('sample_08', 'fact_check', 'ok', '{"score": 95, "breakdown": {"credibility": 40.0, "corroboration": 20, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 5.0, "claims": {"total": 4, "supported": 4, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-130 minutes')),
('sample_09', 'fact_check', 'ok', '{"score": 100, "breakdown": {"credibility": 40.0, "corroboration": 25, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 3, "bestWeight": 5.0, "claims": {"total": 5, "supported": 5, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-190 minutes')),
('sample_10', 'fact_check', 'ok', '{"score": 100, "breakdown": {"credibility": 40.0, "corroboration": 25, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 3, "bestWeight": 5.0, "claims": {"total": 5, "supported": 5, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-300 minutes')),
('sample_11', 'fact_check', 'ok', '{"score": 63, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 10.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 2, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-420 minutes')),
('sample_12', 'fact_check', 'ok', '{"score": 95, "breakdown": {"credibility": 40.0, "corroboration": 20, "primaryEvidence": 20, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 5.0, "claims": {"total": 4, "supported": 4, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-540 minutes')),
('sample_13', 'fact_check', 'ok', '{"score": 68, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 3, "supported": 3, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-1560 minutes')),
('sample_14', 'fact_check', 'ok', '{"score": 68, "breakdown": {"credibility": 28.0, "corroboration": 20, "primaryEvidence": 5, "claimSupport": 15.0, "penalties": 0}, "reasons": [], "independentSources": 2, "bestWeight": 3.5, "claims": {"total": 2, "supported": 2, "contradicted": 0}}', strftime('%Y-%m-%dT%H:%M:%fZ','now','-1700 minutes'));

INSERT INTO article_translations (article_id, lang, headline, summary, what_happened, why_it_matters, figures_dates, affected_entities, risks_uncertainty, grammar_checked, created_at, updated_at) VALUES
('sample_01', 'ka', '[ნიმუში] საქართველოს ეროვნულმა ბანკმა რეფინანსირების განაკვეთი უცვლელი დატოვა', 'ცენტრალურმა ბანკმა მთავარი განაკვეთი უცვლელი დატოვა და განაცხადა, რომ ინფლაცია სამიზნე ტრაექტორიას მიჰყვება.', 'საქართველოს ეროვნული ბანკის მონეტარული პოლიტიკის კომიტეტმა ბოლო სხდომაზე რეფინანსირების განაკვეთი უცვლელი დატოვა. კომიტეტის თქმით, წლიური ინფლაცია სამიზნე მაჩვენებელთან ახლოსაა, შიდა მოთხოვნა კი ზომიერად იზრდება.', 'ქართველი შინამეურნეობებისა და ბიზნესისთვის სესხის ღირებულება ჯერჯერობით იგივე რჩება. უცვლელი განაკვეთი იმასაც ნიშნავს, რომ პოლიტიკის შემქმნელები გაცვლითი კურსის ბოლოდროინდელ ცვლილებებზე რეაგირებას საჭიროდ არ თვლიან.', 'რეფინანსირების განაკვეთი: 8.0%
ინფლაცია: 3.4% წლიური ზრდა
შემდეგი სხდომა: 11 დეკემბერი', 'საქართველოს ეროვნული ბანკი, ქართული ბანკები, მსესხებლები', 'გადაწყვეტილება იმაზეა დამოკიდებული, შენარჩუნდება თუ არა ინფლაციის ტრაექტორია; ლარის მკვეთრმა გაუფასურებამ ან ენერგიის ფასების შოკმა შეიძლება შემდეგ სხდომამდე პროგნოზი შეცვალოს.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-4 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-4 minutes')),
('sample_02', 'ka', '[ნიმუში] ჩიპების მწარმოებელმა მონაცემთა ცენტრებისთვის ინფერენსის ახალი აქსელერატორი წარადგინა', 'ახალი აქსელერატორი გაწვრთნილი მოდელების გასაშვებად შექმნილია და თითო მოთხოვნაზე ნაკლებ ენერგიას მოიხმარს.', 'კომპანიამ მონაცემთა ცენტრებისთვის განკუთვნილი ახალი აქსელერატორი წარადგინა, რომელიც ინფერენსის დატვირთვებისთვისაა შექმნილი. კომპანიის ცნობით, ჩიპი ღრუბლოვან კლიენტებს მომავალ კვარტალში მიეწოდება და წინა თაობასთან შედარებით თითო მოთხოვნაზე ენერგიის მოხმარებას ამცირებს.', 'ინფერენსი ხელოვნური ინტელექტის გამოთვლითი მოთხოვნის ყველაზე დიდ ნაწილად იქცა. მისმა დაბალმა ექსპლუატაციის ხარჯმა შეიძლება შეცვალოს ღრუბლოვანი პროვაიდერების მიერ AI სერვისების ფასდადება და კონკურენტ ჩიპმწარმოებლებზე ზეწოლა გაზარდოს.', 'ხელმისაწვდომობა: მომავალი კვარტალი
ენერგიის დანაზოგი (კომპანიის მტკიცებით): 30% თითო მოთხოვნაზე', 'ღრუბლოვანი პროვაიდერები, ჩიპმწარმოებლები, AI დეველოპერები', 'წარმადობისა და ენერგომოხმარების მაჩვენებლები კომპანიის განცხადებებია და დამოუკიდებლად შემოწმებული არ არის.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-9 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-9 minutes')),
('sample_03', 'ka', '[ნიმუში] Bitcoin-ის სპოტ ETF-ებში კაპიტალის წმინდა შემოდინება სამი დღეა გრძელდება', 'აშშ-ში ბირჟაზე ვაჭრობადმა Bitcoin-ის ფონდებმა ახალი ფული მესამე ზედიზედ სესიაზე მიიღეს.', 'ორი კრიპტო გამოცემის მიერ მოყვანილი ფონდების ნაკადების მონაცემებით, აშშ-ში ბირჟაზე ვაჭრობადმა Bitcoin-ის სპოტ ფონდებმა კაპიტალის წმინდა შემოდინება მესამე ზედიზედ სავაჭრო დღეს დააფიქსირეს. ამავე პერიოდში Bitcoin-ის ფასი გაიზარდა.', 'ETF-ებში ფულის სტაბილური შემოდინება ინსტიტუციური მოთხოვნის ნიშანია, რომელიც Bitcoin-ის ფასის ერთ-ერთ მთავარ მამოძრავებლად იქცა. შემოდინების შეწყვეტა ინტერესის გაცივებაზე მიუთითებდა.', 'წმინდა შემოდინება, ბოლო დღე: 412 მილიონი დოლარი
შემოდინების ზედიზედ დღეები: 3', 'Bitcoin ETF-ების ემიტენტები, კრიპტობირჟები, ინვესტორები', 'ფონდების დღიური მონაცემები ემიტენტების ანგარიშგების მიხედვით კორექტირდება; ერთი დღის მაჩვენებელი ტენდენციის შესახებ შეიძლება შეცდომაში შეგვიყვანოს.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-18 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-18 minutes')),
('sample_04', 'ka', '[ნიმუში] WTO-მ საქონლით გლობალური ვაჭრობის ზრდის პროგნოზი შეამცირა', 'სავაჭრო ორგანიზაციამ პროგნოზი დაწია და მიზეზად სუსტი მოთხოვნა და გაზრდილი ტარიფები დაასახელა.', 'მსოფლიო სავაჭრო ორგანიზაციამ მსოფლიო სასაქონლო ვაჭრობის მოცულობის ზრდის პროგნოზი შეამცირა და მთავარ ეკონომიკებში მოთხოვნის შესუსტება და გაზრდილი ტარიფების ეფექტი დაასახელა. გადახედვა საინფორმაციო სააგენტომაც დაადასტურა.', 'ვაჭრობის ზრდის შენელება ექსპორტიორებსა და გადამზიდავ კომპანიებს აზარალებს და შეიძლება აისახოს წარმოების მოცულობასა და პორტების დატვირთვაზე.', 'პროგნოზის გადახედვა: 0.6 პროცენტული პუნქტით დაბლა
ახალი პროგნოზი: 1.9% მოცულობის ზრდა', 'ექსპორტიორები, გადამზიდავი კომპანიები, წარმოება', 'პროგნოზები მგრძნობიარეა ტარიფებთან დაკავშირებული გადაწყვეტილებების მიმართ, რომლებზეც მოლაპარაკებები ჯერ კიდევ გრძელდება.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-33 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-33 minutes')),
('sample_05', 'ka', '[ნიმუში] ევროპულმა კლიმატ-ტექ სტარტაპმა საშუალო ზომის B სერიის რაუნდი დახურა', 'ბერლინში დაფუძნებულმა კომპანიამ წარმოების გასაფართოებლად ახალი დაფინანსება მოიზიდა.', 'ევროპულმა კლიმატ-ტექნოლოგიურმა სტარტაპმა B სერიის რაუნდის დასრულება გამოაცხადა, რომელსაც არსებული ინვესტორი ხელმძღვანელობდა. ორი ევროპული სტარტაპ-გამოცემის ცნობით, კომპანია თანხას წარმოების გაფართოებასა და ინჟინრების აყვანაზე მიმართავს.', 'კლიმატის სფეროში ფიზიკური აღჭურვილობის კომპანიებისთვის დაფინანსების მოძიება პროგრამულ უზრუნველყოფაზე უფრო რთული იყო. კარგად გამოწერილი რაუნდი მიანიშნებს, რომ ინვესტორები კაპიტალტევად კლიმატურ კომპანიებს, რომლებსაც შემოსავლის ნათელი გზა აქვთ, კვლავ უჭერენ მხარს.', 'რაუნდი: B სერია
მოზიდული თანხა: 45 მილიონი ევრო', 'სტარტაპების ინვესტორები, კლიმატ-ტექ კომპანიები', 'რაუნდის ზომა გამოცემებმა კომპანიის განცხადებებზე დაყრდნობით გამოაქვეყნეს; შეფასება არ გამხელილა.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-47 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-47 minutes')),
('sample_06', 'ka', '[ნიმუში] იპოთეკური განაკვეთები მეორე კვირაა მცირდება', '30-წლიანი იპოთეკის საშუალო განაკვეთი ოდნავ შემცირდა, რაც მყიდველებს მცირე შვებას აძლევს.', 'ორი უძრავი ქონების გამოცემის მიერ მოყვანილი დარგობრივი მონაცემებით, 30-წლიანი ფიქსირებული იპოთეკის საშუალო განაკვეთი მეორე კვირაა ოდნავ მცირდება. შეძენის სესხების განაცხადები ოდნავ გაიზარდა.', 'განაკვეთის მცირე შემცირებაც კი ზრდის იმ მყიდველთა რაოდენობას, რომლებსაც ყოველთვიური გადასახადი შეუძლიათ, და ნელი პერიოდის შემდეგ შეიძლება გაყიდვების მოცულობა გაზარდოს.', '30-წლიანი ფიქსირებულის საშუალო: 6.42%
ცვლილება კვირაში: 0.06 პუნქტით დაბლა', 'ბინის მყიდველები, გამსესხებლები, მშენებლები', 'ერთი კვირის მონაცემი ტენდენცია არ არის; განაკვეთები ობლიგაციების ამონაგებს მიჰყვება, რომელიც სწრაფად შეიძლება შებრუნდეს.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-62 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-62 minutes')),
('sample_07', 'ka', '[ნიმუში] საცალო ბრენდები ბიუჯეტს ფასიანი ძიებიდან კრეატორებთან თანამშრომლობაზე გადააქვთ', 'გამოკითხვით, ბრენდების მზარდი წილი ხარჯებს კრეატორებზე გადაანაწილებს.', 'საცალო მარკეტოლოგების გამოკითხვამ აჩვენა, რომ მზარდი წილი მომავალ წელს ბიუჯეტის ნაწილს ფასიანი ძიებიდან კრეატორებთან პარტნიორობაზე გადაიტანს. შედეგები ორმა პროფესიულმა გამოცემამ გამოაქვეყნა.', 'ძიების ფასი გაიზარდა და ბრენდები ამოწმებენ, კრეატორების კონტენტი მომხმარებლის მოზიდვას უფრო იაფად უზრუნველყოფს თუ არა. სააგენტოები და პლატფორმები თავიანთ შეთავაზებებს არეგულირებენ.', 'ხარჯის გადატანას გეგმავს ბრენდების: 38%
გამოკითხვის პერიოდი: მესამე კვარტალი', 'საცალო ბრენდები, სარეკლამო სააგენტოები, კრეატორების პლატფორმები', 'გამოკითხვის პასუხები განზრახვას ასახავს და არა რეალურ ხარჯს, ხოლო ნიმუშში უფრო მსხვილი ბრენდები სჭარბობს.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-95 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-95 minutes')),
('sample_08', 'ka', '[ნიმუში] საქართველოში წლიური ინფლაცია უკანასკნელ მონაცემებში ოდნავ გაიზარდა', 'სტატისტიკის სამსახურმა სამომხმარებლო ფასების უმნიშვნელო თვიური ზრდა გამოაცხადა.', 'საქართველოს სტატისტიკის ეროვნულმა სამსახურმა (საქსტატი) განაცხადა, რომ სამომხმარებლო ფასები თვის განმავლობაში ოდნავ გაიზარდა და წლიური ინფლაცია პროცენტული პუნქტის მცირე ნაწილით მოიმატა. მთავარი წვლილი სურსათმა და ტრანსპორტმა შეიტანა.', 'ინფლაცია გავლენას ახდენს ცენტრალური ბანკის საპროცენტო გადაწყვეტილებებზე და შინამეურნეობების მსყიდველუნარიანობაზე. სამიზნე მაჩვენებლის ზედა ზღვართან მიახლოება განაკვეთის შემცირების შესაძლებლობას ამცირებს.', 'წლიური ინფლაცია: 3.4%
თვიური ცვლილება: 0.3%-ით მეტი', 'ქართული შინამეურნეობები, საქართველოს ეროვნული ბანკი', 'თვიური მაჩვენებლები მერყევია; სამსახური მონაცემებს ახალი ინფორმაციის შემოსვლისას ასწორებს.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-130 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-130 minutes')),
('sample_09', 'ka', '[ნიმუში] კვლევითმა ლაბორატორიამ ახალი მსჯელობის მოდელის ღია წონები გამოაქვეყნა', 'მოდელი და ტექნიკური ნაშრომი მკვლევრებისთვის გამეორებადად გამოქვეყნდა.', 'კვლევითმა ლაბორატორიამ ახალი მსჯელობის მოდელის წონები გამოაქვეყნა მისი ვარჯიშის აღმწერ რეცენზირებულ ნაშრომთან ერთად. დამოუკიდებელმა გამოცემებმა გამოშვება და ლიცენზიის პირობები დაადასტურეს.', 'ღია წონები უნივერსიტეტებსა და მცირე კომპანიებს მოდელის შესწავლისა და მასზე დაფუძნების საშუალებას აძლევს და შეიძლება დახურული კომერციული მოდელებისთვის მინიმალური სტანდარტი დაადგინოს.', 'პარამეტრები: 70 მილიარდი
ლიცენზია: ლიბერალური, კვლევითი და კომერციული გამოყენებისთვის', 'AI მკვლევრები, ღრუბლოვანი პროვაიდერები, სტარტაპები', 'ნაშრომში მოყვანილი ტესტების შედეგები მესამე მხარეს ჯერ არ გაუმეორებია.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-190 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-190 minutes')),
('sample_10', 'ka', '[ნიმუში] ფედერალურმა სარეზერვო სისტემამ განაკვეთი უცვლელი დატოვა და მოთმინების პოზიცია დააფიქსირა', 'ფედმა მიზნობრივი დიაპაზონი უცვლელი დატოვა და განაცხადა, რომ მეტ მონაცემს დაელოდება.', 'ფედერალური სარეზერვო სისტემის საპროცენტო კომიტეტმა მიზნობრივი დიაპაზონი უცვლელი დატოვა და განაცხადა, რომ მომავალ ნაბიჯებს ინფლაციისა და დასაქმების შემომავალი მონაცემებით შეაფასებს. გადაწყვეტილებაზე საინფორმაციო სააგენტომ და ფინანსურმა გაზეთმა იტყობინა.', 'აშშ-ის განაკვეთები მსოფლიოში სესხის ღირებულებას განსაზღვრავს. მომთმენი ფედი ობლიგაციებისა და ვალუტის ბაზრებისთვის, მათ შორის განვითარებადი ქვეყნებისთვის, სტაბილურ პირობებს უწყობს ხელს.', 'მიზნობრივი დიაპაზონი: 4.25%–4.50%
ხმის მიცემა: ერთხმად', 'აშშ-ის მსესხებლები, ობლიგაციების ბაზრები, განვითარებადი ბაზრების ვალუტები', 'კომიტეტმა აღნიშნა, რომ გზა მონაცემებზეა დამოკიდებული; ინფლაციის ან დასაქმების მოულოდნელმა მაჩვენებელმა მოლოდინები შეიძლება შეცვალოს.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-300 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-300 minutes')),
('sample_11', 'ka', '[ნიმუში] სტეიბლქოინის ემიტენტმა რეზერვების უახლესი დადასტურება გამოაქვეყნა', 'დადასტურება აჩვენებს, რომ რეზერვები მიმოქცევაში მყოფი ტოკენების ღირებულებას აჭარბებს.', 'სტეიბლქოინის მსხვილმა ემიტენტმა რეზერვების ყოველთვიური დადასტურება გამოაქვეყნა, რომელიც დამოუკიდებელმა საბუღალტრო ფირმამ მოამზადა. მის მიხედვით, რეზერვები, ძირითადად მოკლევადიანი სახელმწიფო ვალი, მიმოქცევაში მყოფი ტოკენების ღირებულებას აჭარბებს.', 'რეზერვების გამჭვირვალობა სტეიბლქოინებისადმი ნდობისა და რეგულატორების დამოკიდებულებისთვის მთავარია.', 'რეზერვები ვალდებულებებთან მიმართებით: 102%', 'სტეიბლქოინის მფლობელები, ბირჟები, რეგულატორები', 'დადასტურება ერთი თარიღის მდგომარეობას ასახავს და სრული აუდიტი არ არის.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-420 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-420 minutes')),
('sample_12', 'ka', '[ნიმუში] საქართველოს ფინანსთა სამინისტრომ ევროობლიგაციების განთავსება დაასრულა', 'მთავრობამ საერთაშორისო ბაზრებზე თანხა წინა ემისიაზე დაბალი შემოსავლიანობით მოიზიდა.', 'საქართველოს ფინანსთა სამინისტრომ საერთაშორისო ბაზრებზე ევროობლიგაციების განთავსება დაასრულა. ფინანსური ახალი ამბების სერვისის ცნობით, მოთხოვნამ შეთავაზებულ მოცულობას გადააჭარბა.', 'ნაკლები სასესხო ღირებულება საქართველოს საკრედიტო უნარისადმი ინვესტორთა ნდობას ასახავს და ბიუჯეტის მომავალ საპროცენტო ხარჯებს ამცირებს.', 'მოცულობა: 500 მილიონი დოლარი
ზედმეტი მოთხოვნა: 3-ჯერ', 'საქართველოს მთავრობა, საერთაშორისო ინვესტორები', 'ბაზრის პირობები შეიძლება შეიცვალოს; სამინისტროს განაწილების საბოლოო ცხრილი ჯერ არ გამოუქვეყნებია.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-540 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-540 minutes')),
('sample_13', 'ka', '[ნიმუში] კონტეინერული ტვირთის განაკვეთები მცირდება, რადგან ძირითად მარშრუტებზე მოცულობა ბრუნდება', 'მთავარ მარშრუტებზე სპოტ განაკვეთები ზედიზედ მეოთხე კვირაა ეცემა.', 'აზია–ევროპისა და ტრანსპაციფიკური მთავარი მარშრუტების კონტეინერული ტვირთის სპოტ განაკვეთები ზედიზედ მეოთხე კვირაა ეცემა, რადგან გემების მოცულობა ექსპლუატაციაში ბრუნდება. ეს ორმა სანაოსნო გამოცემამ იტყობინა.', 'ტვირთის დაბალი ღირებულება იმპორტიორებსა და საცალო გამყიდველებს ზეწოლას უმსუბუქებს და გარკვეული დაგვიანებით შეიძლება საქონლის ინფლაციასაც შეამციროს.', 'ინდექსის ცვლილება, კვირა: 5%-ით დაბლა', 'იმპორტიორები, საცალო გამყიდველები, გადამზიდავი ხაზები', 'განაკვეთები სწრაფად შეიძლება გაიზარდოს, თუ შეფერხებები დაბრუნდება ან მოთხოვნა სეზონის პიკამდე გაიზრდება.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-1560 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-1560 minutes')),
('sample_14', 'ka', '[ნიმუში] უნივერსიტეტები მონაცემთა მეცნიერების პროგრამებზე განაცხადების ზრდას აცხადებენ', 'მონაცემებისა და AI პროგრამებზე განაცხადების რაოდენობა გასულ წელთან შედარებით გაიზარდა.', 'რამდენიმე უნივერსიტეტმა მონაცემთა მეცნიერებისა და AI პროგრამებზე წელს მეტი განაცხადის შესახებ იტყობინება, ამბობს ორი საგანმანათლებლო გამოცემა. მოთხოვნა ყველაზე მაღალია ერთწლიან სამაგისტრო პროგრამებზე.', 'კურსდამთავრებულთა დასაქმება და პროგრამების შეთავაზება AI უნარებზე მოთხოვნას ერგება, რაც დამსაქმებელთა დაქირავების გეგმებზე აისახება.', 'განაცხადების ზრდა: 21% გასულ წელთან შედარებით', 'უნივერსიტეტები, დამსაქმებლები, აბიტურიენტები', 'განაცხადების რაოდენობა არ აჩვენებს, რამდენი სტუდენტი ჩაირიცხება ან დაამთავრებს პროგრამას.', 1, strftime('%Y-%m-%dT%H:%M:%fZ','now','-1700 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-1700 minutes'));


-- Sample charts (numbers taken from the sample stories' own figures) and the cited feed items,
-- so the story page shows its chart and its "how the reporting developed" timeline.
INSERT INTO article_charts (article_id, lang, data, created_at) VALUES
('sample_01', 'en', '{"title":"Policy rate and inflation","unit":"%","items":[{"label":"Refinancing rate","value":8.0},{"label":"Inflation, year on year","value":3.4}]}', strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('sample_01', 'ka', '{"title":"საპროცენტო განაკვეთი და ინფლაცია","unit":"%","items":[{"label":"რეფინანსირების განაკვეთი","value":8.0},{"label":"ინფლაცია, წლიური","value":3.4}]}', strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('sample_04', 'en', '{"title":"World goods trade forecast","unit":"%","items":[{"label":"New volume growth forecast","value":1.9},{"label":"Downward revision, points","value":0.6}]}', strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('sample_04', 'ka', '{"title":"მსოფლიო საქონლით ვაჭრობის პროგნოზი","unit":"%","items":[{"label":"ზრდის ახალი პროგნოზი","value":1.9},{"label":"შემცირება, პროცენტული პუნქტი","value":0.6}]}', strftime('%Y-%m-%dT%H:%M:%fZ','now'));

INSERT INTO feed_items (id, source_id, source_name, feed_id, title, url, snippet, published_at, fetched_at, article_id) VALUES
('sample_f1', 'nbg', 'National Bank of Georgia', 'nbg-news', 'NBG press release: Monetary Policy Committee decision', 'https://nbg.gov.ge/en/media/news', NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now','-125 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-120 minutes'), 'sample_01'),
('sample_f2', 'civil-ge', 'Civil.ge', 'civil-ge', 'Georgia''s central bank keeps rate on hold', 'https://civil.ge/', NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now','-105 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-100 minutes'), 'sample_01'),
('sample_f3', 'wto', 'WTO', 'wto', 'WTO: updated trade forecast', 'https://www.wto.org/', NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now','-48 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-45 minutes'), 'sample_04'),
('sample_f4', 'reuters', 'Reuters', 'reuters', 'WTO cuts global trade growth forecast', 'https://www.reuters.com/', NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now','-39 minutes'), strftime('%Y-%m-%dT%H:%M:%fZ','now','-36 minutes'), 'sample_04');
