// Turns schema.sql into src/schema.ts so the Worker can create its own tables on first use.
// Runs as part of `npm run build` (and therefore on every Cloudflare build), and a test fails
// if the committed src/schema.ts ever drifts from schema.sql.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const sql = readFileSync(new URL('../schema.sql', import.meta.url), 'utf8');
const statements = sql
  .replace(/--.*$/gm, '') // comments
  .split(';')
  .map((s) => s.replace(/\s+/g, ' ').trim())
  .filter(Boolean);

const out = new URL('../src/schema.ts', import.meta.url);
const body = `// GENERATED by scripts/gen-schema.mjs from schema.sql. Do not edit by hand.\nexport const SCHEMA_STATEMENTS: string[] = ${JSON.stringify(statements, null, 2)};\n`;

// Only write when the content changed. `wrangler dev` re-runs the build whenever a file under src/ changes,
// so rewriting an identical file would make the dev server rebuild forever.
if (!existsSync(out) || readFileSync(out, 'utf8') !== body) writeFileSync(out, body);
console.log(`schema.ts: ${statements.length} statements`);
